### ISSUE TITLE
English 1 loading issue

### ISSUE THREAD

**Issue by space66666** [iwantavnow/Setting.App-Android#3]
In English 1 Channel, video and video detail thumbnails will not load after 4 to 5 video detail viewed. But once you load a new page, the view count will restart so I can view 4-5 time again. Please fix this issue as it is very frustrating, suspect it is cause by session.

**Comment by Zxcvbnm3748755** [comment]
为什么我的云端版被删除之后无法恢复

**Comment by Zxcvbnm3748755** [comment]
设置里面没有恢复云端版，所以，我很难受

**Comment by godderkimo0730** [comment]
> In English 1 Channel, video and video detail thumbnails will not load after 4 to 5 video detail viewed. But once you load a new page, the view count will restart so I can view 4-5 time again. Please fix this issue as it is very frustrating, suspect it is cause by session.

**Comment by iwantavnow** [comment]
Fix on 8.10.9
